### ISSUE TITLE
Blender python script file missing?

### ISSUE THREAD

**Issue by nessaki** [SudeepRed/MatchUp_V2#1]
Hello,
I am trying to use the wonderful solution you came up with but I can't seem to find any python script files that were mentioned.  Any assistance would be appreciated. Thank you

**Comment by SudeepRed** [comment]
Hey!
The script file is in a separate repo.
Glad you liked my project!
[Here is the script](https://github.com/SudeepRed/ShapeKeyTransfer_Addon_Blender)
